### ISSUE TITLE
[PE-D][Tester D] editMeeting unable to remove description of meeting

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-F08-1/tp#238]
Unable to remove description of meeting following the format given in user guide.

steps to reproduce:
1. execute: `editMeeting clientIndex/2 meetingIndex/1 d/`

![image.png](https://raw.githubusercontent.com/ZhiWei1010/ped/main/files/a21d62d1-7d80-4368-b465-e28ab8f67bd8.png)

![image.png](https://raw.githubusercontent.com/ZhiWei1010/ped/main/files/eea16d09-0ac9-48a9-b927-712ad52486ee.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: ZhiWei1010/ped#20

**Comment by timothysashimi** [comment]
Thank you for pointing this out. Actually it was a documentation error as the editMeeting command needs all parameters present to be parsed (client index, meeting index, description and datetime). The description of the meeting cannot be null so that only meaningful meetings can be entered. As financial advisors, every second is precious. Hence we've edited the user guide as well as included an error message if any of the parameters are missing.
